// Catalogue des plateformes utilisées par l'équipe, avec un guide d'utilisation pour chacune.
// « integration » décrit honnêtement le lien possible avec ImmoPilot.

export interface PlatformGuide {
  key: string; name: string; url: string; domain: string; category: string; usage: string
  what: string; when: string[]; how: string[]; tips?: string[]
  integration: { level: 'lien' | 'export' | 'api'; text: string }
  source?: string
}

export const PLATFORM_CATALOG: PlatformGuide[] = [
  // ---------- Inscriptions, transactions & données ----------
  { key: 'centris', name: 'Centris', url: 'https://www.centris.ca', domain: 'centris.ca', category: 'Inscriptions & transactions', usage: 'Inscriptions, saisie à la source, avis de vente',
    what: 'Système d’inscriptions des courtiers au Québec (saisie à la source des inscriptions, avis de vente, statistiques).',
    when: ['Nouveau dossier vendeur : faire l’inscription (saisie à la source).', 'Conditions réalisées : faire l’avis de vente.'],
    how: ['Préparer la fiche complète dans ImmoPilot (Inscriptions → Caractéristiques, Pièces, Documents).', 'Imprimer la fiche ImmoPilot et saisir les données dans Centris.', 'Inscrire le numéro Centris dans la fiche ImmoPilot pour le retrouver partout.'],
    integration: { level: 'lien', text: 'Pas d’API publique pour les courtiers : ImmoPilot prépare toutes les données (fiche imprimable, mesures des pièces) pour une saisie rapide.' } },
  { key: 'rechat', name: 'Rechat', url: 'https://app.rechat.com/', domain: 'rechat.com', category: 'Inscriptions & transactions', usage: 'CRM, marketing et transactions',
    what: 'Plateforme « tout-en-un » utilisée par plusieurs réseaux immobiliers : contacts (People), marketing et design (Studio), transactions et inscriptions (Deals) et une assistante IA (Lucy).',
    when: ['Dès qu’une inscription est mise en ligne : Rechat peut générer automatiquement des visuels, courriels, dépliants et un site web de la propriété.', 'Pour les campagnes courriel et publications aux couleurs de votre bannière.', 'Pour les pages d’inscription aux visites libres (open house sign-in).'],
    how: ['Se connecter avec le compte fourni par votre bannière (SSO).', 'People : importer / synchroniser les contacts et créer des « Flows » (séquences automatiques).', 'Studio : choisir un modèle aux couleurs de la marque → personnaliser → publier ou envoyer.', 'Deals : créer le dossier d’inscription ou d’achat et suivre les documents.'],
    tips: ['Utiliser ImmoPilot pour le terrain (visites, mesures, SOP) et Rechat pour le marketing de marque de votre bannière.'],
    integration: { level: 'export', text: 'Exporter vos contacts ImmoPilot en CSV (Contacts → Exporter) puis les importer dans Rechat People.' },
    source: 'https://rechat.ai/' },

  { key: 'nexone', name: 'NexOne Office', url: 'https://office.nexone.ca/apex/f?p=100:101', domain: 'nexone.ca', category: 'Inscriptions & transactions', usage: 'Back-office de l’agence : transactions, comptabilité, dossiers',
    what: 'Logiciel québécois de gestion des transactions (TMS), de la comptabilité et des dossiers de courtage pour agences : déclarations de transactions, déboursés, documents, conformité.',
    when: ['P.A. acceptée : ouvrir/déclarer la transaction au bureau.', 'Dossier électronique complet (GED) et déboursés de commission.'],
    how: ['Se connecter à NexOne Office avec le compte de l’agence.', 'Créer ou compléter la déclaration de transaction avec les informations du dossier ImmoPilot (prix, dates, parties, rétribution).', 'Téléverser les documents requis et suivre l’approbation.'],
    integration: { level: 'lien', text: 'Accès en un clic; le dossier ImmoPilot (Dossiers & transactions) contient les dates, parties et montants à reporter.' },
    source: 'https://nexone.ca/fr/' },
  { key: 'ezsign', name: 'eZsign / eZmax', url: 'https://www.ezmax.ca/fr/courtiers/signature-electronique', domain: 'ezmax.ca', category: 'Inscriptions & transactions', usage: 'Signature électronique des contrats et formulaires',
    what: 'Solution de signature électronique conforme aux exigences de l’OACIQ. Les clients signent sur ordinateur, tablette ou téléphone avec un code de validation reçu par texto.',
    when: ['Contrat de courtage vente ou achat (6 mois), promesses d’achat, annexes, accusés de réception.'],
    how: ['Préparer le formulaire (InstanetForms ou modèle).', 'Envoyer à eZsign, définir l’ordre des signataires.', 'Chaque signataire reçoit un code par texto, signe en un clic et reçoit sa copie.', 'Cocher l’étape dans le dossier ImmoPilot (ex. « Contrat de courtage signé »).'],
    integration: { level: 'lien', text: 'Accès en un clic; les étapes de signature sont suivies dans les processus vendeur et acheteur d’ImmoPilot.' },
    source: 'https://ezmax.ca/fr/courtiers/signature-electronique' },
  { key: 'immocontact', name: 'Immocontact', url: 'https://immocontact.com/', domain: 'immocontact.com', category: 'Inscriptions & transactions', usage: 'Demandes et confirmations de visites',
    what: 'Messagerie immobilière des courtiers : demandes et confirmations de visites, rapports et avis sur les propriétés. Depuis le 1er mai 2026, offerte directement aux courtiers (hors Centris), sans perte de données.',
    when: ['Nouveau dossier vendeur : gérer Immocontact (demandes de visites).', 'Chaque visite d’acheteur que vous organisez.'],
    how: ['Configurer les plages de visite pré-approuvées (les demandes dans une plage libre sont approuvées automatiquement).', 'Une adjointe peut envoyer des demandes au nom du courtier en changeant de profil.', 'Après chaque visite : consigner la rétroaction dans ImmoPilot (Visites & rétroactions).'],
    integration: { level: 'lien', text: 'Accès en un clic; l’horaire des visites de la fiche ImmoPilot sert à configurer les plages.' },
    source: 'https://immocontact.com/faq' },
  { key: 'jlr', name: 'JLR', url: 'https://www.jlr.ca/me-connecter', domain: 'jlr.ca', category: 'Inscriptions & transactions', usage: 'Comparables, transactions, profils de propriété',
    what: 'Données foncières du Québec : profils de propriété, recherche de transactions (y compris ventes privées), évaluations automatisées, alertes et générateur de comparables (ratio prix/évaluation municipale).',
    when: ['Préparation du RDV vendeur (SOP étape 1) : comparables et ventes récentes.', 'Analyse comparative du marché (Guide vendeur étape 4).', 'Prospection de propriétaires.'],
    how: ['Rechercher l’adresse → profil de la propriété (propriétaires, évaluation, historique).', 'Générer le rapport de comparables (ventes récentes similaires à proximité).', 'Joindre les chiffres clés à l’inscription ImmoPilot (notes) pour la présentation du prix.'],
    integration: { level: 'lien', text: 'Accès en un clic; les résultats alimentent la stratégie de prix (Juste prix / Chance / Boxing Day).' },
    source: 'https://solutions.jlr.ca/fr/courtier-immobilier' },
  { key: 'registre', name: 'Registre foncier du Québec', url: 'https://www.registrefoncier.gouv.qc.ca/Sirf/', domain: 'registrefoncier.gouv.qc.ca', category: 'Inscriptions & transactions', usage: 'Actes, titres, index des immeubles',
    what: 'Registre officiel des droits sur les immeubles : index des immeubles, actes (vente, hypothèque, servitudes), plans cadastraux.',
    when: ['Vérifier le propriétaire et les droits avant la prise d’inscription.', 'Obtenir l’acte de vente ou une servitude pour le dossier.'],
    how: ['Se connecter avec le compte client (frais à la consultation).', 'Rechercher par numéro de lot (index des immeubles) puis ouvrir les actes pertinents.', 'Déposer les documents dans la GED de l’agence et cocher dans ImmoPilot.'],
    integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'oaciq', name: 'OACIQ', url: 'https://www.oaciq.com', domain: 'oaciq.com', category: 'Inscriptions & transactions', usage: 'Formulaires, règles et guides de pratique',
    what: 'Organisme d’autoréglementation du courtage immobilier au Québec : formulaires obligatoires, guides de pratique, règles (ex. signatures électroniques).',
    when: ['Valider les formulations (ex. technique FBI, rétribution) et les obligations professionnelles.'],
    how: ['Consulter la section Courtier → guides de pratique et formulaires.'],
    integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'apciq', name: 'APCIQ', url: 'https://apciq.ca/', domain: 'apciq.ca', category: 'Inscriptions & transactions', usage: 'Association, statistiques de marché',
    what: 'Association professionnelle des courtiers immobiliers du Québec : statistiques de marché, formations, services aux membres.',
    when: ['Données de marché pour la démonstration d’expertise locale (SOP étape 4).'],
    how: ['Consulter les statistiques par région et les intégrer à la présentation vendeur.'],
    integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'realtor', name: 'Realtor.ca', url: 'https://www.realtor.ca', domain: 'realtor.ca', category: 'Diffusion', usage: 'Diffusion nationale des inscriptions',
    what: 'Portail national de l’ACI où les inscriptions sont diffusées.', when: ['Mise en marché : vérifier la diffusion de l’inscription.'],
    how: ['Rechercher le numéro d’inscription et vérifier photos et informations.'], integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'properstar', name: 'Properstar', url: 'https://www.properstar.ca/', domain: 'properstar.ca', category: 'Diffusion', usage: 'Diffusion internationale des propriétés',
    what: 'Plateforme internationale (ListGlobally, Suisse) qui diffuse les inscriptions sur un réseau de portails dans plus de 60 pays.',
    when: ['Propriétés de prestige ou susceptibles d’intéresser des acheteurs étrangers (plan marketing).'],
    how: ['Se connecter à l’espace professionnel, vérifier que l’inscription est bien syndiquée, suivre les demandes internationales.'],
    integration: { level: 'lien', text: 'Accès en un clic; cochez « Diffusion » dans le plan marketing de l’inscription.' },
    source: 'https://www.properstar.ca/' },
  { key: 'duproprio', name: 'DuProprio', url: 'https://duproprio.com', domain: 'duproprio.com', category: 'Prospection', usage: 'Veille / prospection des ventes sans courtier',
    what: 'Portail des propriétés vendues sans courtier.', when: ['Prospection de vendeurs (FSBO) et veille de prix.'],
    how: ['Repérer les propriétés du secteur, noter les coordonnées dans ImmoPilot (Contacts → source « DuProprio ») et planifier un suivi.'],
    integration: { level: 'lien', text: 'Accès en un clic; source « DuProprio » disponible dans les contacts.' } },
  { key: 'prospects', name: 'Prospects (CRM)', url: 'https://qc.prospects.com/prospects/logon.do', domain: 'prospects.com', category: 'Prospection', usage: 'CRM relié à Centris, fiches et plans d’action',
    what: 'CRM et application mobile de Logiciels Prospects, reliés aux inscriptions Centris : fiches clients, recherches, plans d’action automatiques (fête, Noël…).',
    when: ['Nouveau dossier vendeur, étape 1 : entrer le client dans Prospects et démarrer le plan d’action.'],
    how: ['Créer la fiche du client (ou vérifier la fiche d’un ancien client).', 'Démarrer le plan d’action (fête, Noël, anniversaire d’achat).'],
    tips: ['ImmoPilot calcule aussi les fêtes et anniversaires d’achat sur le tableau de bord.'],
    integration: { level: 'export', text: 'Exporter / importer les contacts en CSV entre Prospects et ImmoPilot.' },
    source: 'https://www.prospects.com/fr/ca/a-propos/' },
  { key: 'monprospecteur', name: 'Mon Prospecteur', url: 'https://www.monprospecteur.com/', domain: 'monprospecteur.com', category: 'Prospection', usage: 'Listes d’opportunités issues du registre foncier',
    what: 'Outil québécois qui analyse le registre foncier et envoie des propriétés à fort potentiel sur un territoire défini (successions, préavis, etc.).',
    when: ['Prospection de propriétaires vendeurs potentiels et d’investisseurs.'],
    how: ['Définir le territoire sur la carte, recevoir les listes, importer les contacts ciblés dans ImmoPilot (CSV) et lancer le script de prospection.'],
    integration: { level: 'export', text: 'Import CSV dans Contacts.' }, source: 'https://www.monprospecteur.com/' },

  // ---------- Marketing ----------
  { key: 'activepipe', name: 'ActivePipe', url: 'https://auth.activepipe.com/sso/openid/google', domain: 'activepipe.com', category: 'Marketing', usage: 'Courriels automatisés et détection d’intention',
    what: 'Plateforme de courriels automatisés pour l’immobilier : infolettres personnalisées, alertes de propriétés, détection des signaux d’intention d’achat/vente selon l’engagement.',
    when: ['Nouvelle inscription : envoyer au réseau d’acheteurs.', 'Suivi de la base de données (sphère, anciens clients).'],
    how: ['Se connecter (SSO Google).', 'Importer/synchroniser les contacts, choisir un modèle, programmer l’envoi.', 'Consulter les contacts « chauds » (intention) et créer une tâche de suivi dans ImmoPilot.'],
    integration: { level: 'export', text: 'Export CSV des contacts ImmoPilot vers ActivePipe.' }, source: 'https://activepipe.com/' },
  { key: 'mailchimp', name: 'Mailchimp', url: 'https://login.mailchimp.com', domain: 'mailchimp.com', category: 'Marketing', usage: 'Infolettres',
    what: 'Outil d’infolettres et d’automatisations courriel.', when: ['Infolettres mensuelles, annonces de nouvelles inscriptions.'],
    how: ['Importer l’audience (CSV ImmoPilot), créer la campagne, envoyer ou planifier.'], integration: { level: 'export', text: 'Export CSV des contacts.' } },
  { key: 'canva', name: 'Canva', url: 'https://www.canva.com/fr_fr/', domain: 'canva.com', category: 'Marketing', usage: 'Visuels RS, fiches, présentations',
    what: 'Outil de design en ligne.', when: ['Publications « Nouveauté », « Vendu », cahier de présentation vendeur, pancarte virtuelle (Annexe B du SOP).'],
    how: ['Utiliser un modèle de marque, insérer photos et textes générés par ImmoPilot (Marketing → Générer depuis le modèle), exporter.'],
    integration: { level: 'lien', text: 'Accès en un clic; les légendes sont générées dans ImmoPilot.' } },
  { key: 'artlist', name: 'Artlist.io', url: 'https://artlist.io', domain: 'artlist.io', category: 'Marketing', usage: 'Musique libre de droits',
    what: 'Banque de musique et effets libres de droits.', when: ['Reels et vidéos de présentation de propriétés.'], how: ['Télécharger la piste, l’ajouter au montage.'], integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'fiverr', name: 'Fiverr', url: 'https://www.fiverr.com', domain: 'fiverr.com', category: 'Marketing', usage: 'Montage, virtual staging, graphisme',
    what: 'Marché de pigistes.', when: ['Virtual staging, montage vidéo, plans 2D/3D à partir du plan ImmoPilot.'], how: ['Commander le service, fournir les médias exportés de la visite ImmoPilot (photos, vidéos, plan).'], integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'vistaprint', name: 'Vistaprint', url: 'https://www.vistaprint.ca', domain: 'vistaprint.ca', category: 'Marketing', usage: 'Cartes, dépliants, envois postaux',
    what: 'Impression en ligne.', when: ['Dépliants de secteur, cartes d’affaires, envois postaux (plan marketing).'], how: ['Téléverser le visuel Canva, commander, consigner la dépense.'], integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'napart', name: 'Nap-Art', url: 'https://www.nap-art.com/', domain: 'nap-art.com', category: 'Marketing', usage: 'Impression / cadeaux clients',
    what: 'Impression et produits promotionnels.', when: ['Cadeau ou attention à remettre au vendeur (SOP).'], how: ['Commander, consigner la dépense dans ImmoPilot.'], integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'pancarte', name: 'Pancarte Express', url: 'https://pancarteexpress.com/mon-compte/', domain: 'pancarteexpress.com', category: 'Marketing', usage: 'Pancartes À vendre / Vendu + boîtes à clé',
    what: 'Installation et retrait de pancartes, accessoires et boîtes à clé (Montréal). Le compte donne accès aux tarifs par territoire, photos de confirmation d’installation, historique et facturation mensuelle.',
    when: ['Nouveau dossier vendeur : commander pancarte + boîte à clé.', 'P.A. acceptée : commander la pancarte « VENDU ».', 'Après l’acte : retrait.'],
    how: ['Se connecter à « Mon compte », faire la demande d’installation (adresse, date, accessoires, code de la boîte à clé).', 'Vérifier la photo de confirmation, cocher l’étape dans le dossier ImmoPilot.'],
    integration: { level: 'lien', text: 'Accès en un clic; l’étape est dans le processus vendeur ImmoPilot.' }, source: 'https://pancarteexpress.com/' },

  // ---------- Réseaux sociaux ----------
  { key: 'facebook', name: 'Facebook', url: 'https://www.facebook.com', domain: 'facebook.com', category: 'Réseaux sociaux', usage: 'Publications, publicités, groupes', what: 'Réseau social et publicité (Meta).', when: ['Nouveauté à vendre, visite libre, vendu, publicités ciblées.'], how: ['Publier depuis Meta Business Suite avec la légende générée par ImmoPilot.'], integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'instagram', name: 'Instagram', url: 'https://www.instagram.com', domain: 'instagram.com', category: 'Réseaux sociaux', usage: 'Posts, reels, stories', what: 'Réseau social visuel.', when: ['Reels de propriétés, stories (taguer LP avec le café du client — SOP).'], how: ['Publier le reel, copier la légende d’ImmoPilot, marquer « Publié » dans le calendrier marketing.'], integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'tiktok', name: 'TikTok', url: 'https://www.tiktok.com', domain: 'tiktok.com', category: 'Réseaux sociaux', usage: 'Vidéos courtes', what: 'Vidéos courtes.', when: ['Visites vidéo rapides, coulisses.'], how: ['Réutiliser les vidéos de pièces filmées pendant la visite ImmoPilot.'], integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'linkedin', name: 'LinkedIn', url: 'https://www.linkedin.com', domain: 'linkedin.com', category: 'Réseaux sociaux', usage: 'Réseau professionnel', what: 'Réseau professionnel.', when: ['Investisseurs, commercial, relocalisation.'], how: ['Partager les inscriptions et statistiques de marché.'], integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'youtube', name: 'YouTube', url: 'https://studio.youtube.com', domain: 'youtube.com', category: 'Réseaux sociaux', usage: 'Visites vidéo', what: 'Hébergement vidéo.', when: ['Vidéo de présentation, visite virtuelle.'], how: ['Téléverser la vidéo, coller le lien dans la fiche descriptive.'], integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'gbp', name: 'Google Business Profile', url: 'https://business.google.com', domain: 'google.com', category: 'Réseaux sociaux', usage: 'Avis Google, fiche d’entreprise', what: 'Fiche Google de l’équipe.', when: ['Après la vente : demander un avis (processus vendeur, dernière étape).'], how: ['Copier le lien d’avis et l’envoyer au client avec un modèle ImmoPilot.'], integration: { level: 'lien', text: 'Accès en un clic.' } },

  // ---------- Communication & administration ----------
  { key: 'gmail', name: 'Gmail (équipe)', url: 'https://mail.google.com', domain: 'gmail.com', category: 'Communication & administration', usage: 'Courriels courtiers, marketing, admin, info', what: 'Messagerie de l’équipe.', when: ['Tous les échanges clients.'], how: ['Les modèles ImmoPilot ouvrent directement un courriel pré-rempli.'], integration: { level: 'lien', text: 'Ouverture de courriels pré-remplis (mailto) depuis ImmoPilot.' } },
  { key: 'calendly', name: 'Calendly', url: 'https://calendly.com', domain: 'calendly.com', category: 'Communication & administration', usage: 'Prise de rendez-vous clients', what: 'Prise de rendez-vous en ligne.', when: ['RDV d’évaluation vendeur, consultation acheteur.'], how: ['Partager le lien Calendly; ajouter le RDV au calendrier ImmoPilot (ou importer via .ics).'], integration: { level: 'lien', text: 'Export .ics d’ImmoPilot vers votre agenda.' } },
  { key: 'icloud', name: 'iCloud (tél. marketing)', url: 'https://www.icloud.com', domain: 'icloud.com', category: 'Communication & administration', usage: 'Téléphone marketing, photos', what: 'Compte Apple du téléphone marketing.', when: ['Récupérer photos et vidéos du téléphone marketing.'], how: ['Télécharger les médias puis les joindre à la visite ou à l’inscription.'], integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'godaddy', name: 'GoDaddy', url: 'https://www.godaddy.com', domain: 'godaddy.com', category: 'Communication & administration', usage: 'Domaines et courriels', what: 'Domaines web.', when: ['Renouvellement de domaines.'], how: ['Gérer les DNS et renouvellements.'], integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'paies', name: 'Paies — gestion Jim', url: '', domain: '', category: 'Communication & administration', usage: 'Paies et comptabilité', what: 'Service de paie externe.', when: ['Fin de mois.'], how: ['Exporter les dépenses CSV depuis ImmoPilot → Commissions & dépenses.'], integration: { level: 'export', text: 'Export CSV des dépenses.' } },
  { key: 'chatgpt', name: 'ChatGPT', url: 'https://chatgpt.com', domain: 'chatgpt.com', category: 'Communication & administration', usage: 'Rédaction de textes', what: 'Assistant de rédaction.', when: ['Descriptions de propriétés, publications.'], how: ['Coller les caractéristiques de la fiche ImmoPilot et demander une description.'], integration: { level: 'lien', text: 'Accès en un clic.' } },
  { key: 'streetview', name: 'Google Street View', url: 'https://www.google.com/maps', domain: 'maps.google.com', category: 'Communication & administration', usage: 'Préparation RDV — parcourir le quartier', what: 'Cartes et Street View.', when: ['SOP étape 1 : parcourir le quartier avant le RDV.'], how: ['Bouton « Street View / carte » dans chaque inscription ImmoPilot.'], integration: { level: 'lien', text: 'Lien direct depuis chaque inscription.' } },
]

export const guideFor = (p: { name: string; url: string; key?: string }) =>
  PLATFORM_CATALOG.find(g => (p.key && g.key === p.key) || g.name === p.name || (p.url && g.url && new URL(g.url, 'https://x').hostname === safeHost(p.url)))
function safeHost(u: string) { try { return new URL(u).hostname } catch { return '' } }

// Outils affichés sur la page d'accueil (logos)
export const INTEGRATION_LOGOS: { name: string; domain: string }[] = [
  { name: 'Calendly', domain: 'calendly.com' }, { name: 'Google Agenda', domain: 'calendar.google.com' }, { name: 'Gmail', domain: 'gmail.com' },
  { name: 'Outlook', domain: 'outlook.com' }, { name: 'Centris', domain: 'centris.ca' }, { name: 'Realtor.ca', domain: 'realtor.ca' },
  { name: 'Rechat', domain: 'rechat.com' }, { name: 'NexOne', domain: 'nexone.ca' }, { name: 'eZsign', domain: 'ezmax.ca' },
  { name: 'JLR', domain: 'jlr.ca' }, { name: 'Immocontact', domain: 'immocontact.com' }, { name: 'Prospects', domain: 'prospects.com' },
  { name: 'ActivePipe', domain: 'activepipe.com' }, { name: 'Mailchimp', domain: 'mailchimp.com' }, { name: 'Canva', domain: 'canva.com' },
  { name: 'Properstar', domain: 'properstar.ca' }, { name: 'DuProprio', domain: 'duproprio.com' }, { name: 'Facebook', domain: 'facebook.com' },
  { name: 'Instagram', domain: 'instagram.com' }, { name: 'TikTok', domain: 'tiktok.com' }, { name: 'LinkedIn', domain: 'linkedin.com' },
  { name: 'YouTube', domain: 'youtube.com' }, { name: 'Google Business', domain: 'business.google.com' }, { name: 'Pancarte Express', domain: 'pancarteexpress.com' },
]
export const logoUrl = (domain: string, size = 128) => `https://www.google.com/s2/favicons?domain=${domain}&sz=${size}`
