import { useEffect, useRef, useState } from 'react'
import { MessageCircle, Plus, Send, ArrowLeft, Camera, Smile } from 'lucide-react'
interface Person {id:string;name:string;avatar:string}
interface Thread {id:string;kind:string;title:string;members:string[];createdBy:string;updatedAt:string;read:Record<string,string>}
interface Message {id:string;sender:string;text:string;at:string;reactions:Record<string,string[]>}
interface Inbox {me:Person;support:boolean;people:Person[];peers:Person[];threads:Thread[];messages:Message[]}
async function call(body?:object,thread=''){const r=await fetch('/api/messages'+(thread?'?thread='+encodeURIComponent(thread):''),body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:undefined);const b=await r.json();if(!r.ok)throw new Error(b.error||'Erreur');return b}
const emojis=['❤️','👍','😂','🎉','😮','🙏']
function Pic({p}:{p?:Person}){return p?.avatar?<img className="chat-avatar" src={p.avatar} alt={p.name}/>:<span className="chat-avatar">{p?.name.slice(0,2).toUpperCase()||'IP'}</span>}
export default function Messages(){
 const [data,setData]=useState<Inbox|null>(null),[id,setId]=useState(''),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[creating,setCreating]=useState(false),[kind,setKind]=useState('direct'),[members,setMembers]=useState<string[]>([]),[title,setTitle]=useState(''),[emojiOpen,setEmojiOpen]=useState(false),[rename,setRename]=useState(false)
 const generation=useRef(0),bottom=useRef<HTMLDivElement>(null)
 useEffect(()=>{const version=++generation.current;setData(d=>d?{...d,messages:[]}:d);let pending=false;const load=async()=>{if(pending)return;pending=true;try{const b=await call(undefined,id);if(version===generation.current){setData(b);setError('')}}catch(e){if(version===generation.current)setError((e as Error).message)}finally{pending=false}};void load();const t=setInterval(()=>{if(document.visibilityState==='visible')void load()},5000);return()=>{generation.current++;clearInterval(t)}},[id])
 useEffect(()=>{bottom.current?.scrollIntoView({block:'nearest'});if(id&&data?.messages.length)void call({action:'read',id}).catch(()=>undefined)},[id,data?.messages.length])
 const refresh=async()=>{const version=generation.current;const next=await call(undefined,id);if(version===generation.current)setData(next)}
 const run=async(body:object,after?:(b:any)=>void)=>{setBusy(true);setError('');try{const b=await call(body);await refresh();after?.(b)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const upload=async(file?:File)=>{if(!file)return;setBusy(true);try{if(!/^image\/(jpeg|png|webp)$/.test(file.type)||file.size>10000000)throw new Error('Choisissez une image JPG, PNG ou WebP (10 Mo maximum).');const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;const ctx=canvas.getContext('2d')!;const size=Math.min(bitmap.width,bitmap.height);ctx.drawImage(bitmap,(bitmap.width-size)/2,(bitmap.height-size)/2,size,size,0,0,256,256);bitmap.close();await call({action:'avatar',avatar:canvas.toDataURL('image/jpeg',0.85)});await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!data)return <div className="card p-5">{error||'Chargement de la messagerie…'}</div>
 const person=(pid:string)=>data.people.find(p=>p.id===pid)
 const current=data.threads.find(t=>t.id===id)
 const label=(t:Thread)=>t.kind==='support'?(data.support?`ImmoPilot · ${person(t.members[0])?.name??'Client'}`:'ImmoPilot'):t.kind==='group'?t.title:person(t.members.find(m=>m!==data.me.id)??'')?.name??'Conversation'
 return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-semibold">Messagerie</h1><label className="btn-outline cursor-pointer"><Camera size={16}/>Ma photo<input aria-label="Ma photo de profil" type="file" accept="image/jpeg,image/png,image/webp" hidden disabled={busy} onChange={e=>{void upload(e.target.files?.[0]);e.target.value=''}}/></label></div>{error&&<p role="alert" className="rounded-xl bg-rose-50 p-3 text-rose-700">{error}</p>}
 <div className={`chat-shell card ${id?'chat-selected':''}`}><aside className="chat-list"><div className="flex items-center gap-2 p-4"><Pic p={data.me}/><strong className="min-w-0 flex-1 truncate">{data.me.name}</strong><button className="btn-ghost" aria-label="Nouvelle conversation" onClick={()=>{setCreating(true);setTitle('');setMembers([])}}><Plus size={18}/></button></div>{!data.support&&<button className="chat-thread" disabled={busy} onClick={()=>run({action:'create',kind:'support',members:[]},b=>setId(b.id))}><MessageCircle size={22}/><span>Contacter ImmoPilot</span></button>}
 {data.threads.map(t=><button key={t.id} className={`chat-thread ${t.id===id?'selected':''}`} onClick={()=>{setId(t.id);setRename(false)}}><Pic p={t.kind==='direct'?person(t.members.find(m=>m!==data.me.id)??''):undefined}/><span className="min-w-0 flex-1 text-left"><strong className="block truncate">{label(t)}</strong><small>{t.kind==='group'?`${t.members.length} membres`:t.kind==='support'?'Assistance privée':'Conversation privée'}</small></span>{t.updatedAt>(t.read[data.me.id]??'')&&<span className="h-2 w-2 rounded-full bg-blue-500" aria-label="Non lu"/>}</button>)}{!data.threads.length&&<p className="p-4 text-sm text-slate-500">Vos conversations apparaîtront ici.</p>}</aside>
 <section className="chat-panel">{!current?<div className="flex flex-1 flex-col items-center justify-center gap-3 p-8 text-center"><MessageCircle size={40}/><h2 className="text-xl">Votre équipe, au même endroit</h2><p>Messages privés, groupes et assistance ImmoPilot.</p><button className="btn-primary" onClick={()=>setCreating(true)}>Nouvelle conversation</button></div>:<><header className="flex items-center gap-3 border-b border-slate-200 p-4"><button className="btn-ghost md:hidden" aria-label="Retour aux conversations" onClick={()=>setId('')}><ArrowLeft size={20}/></button><div className="min-w-0 flex-1"><h2 className="truncate font-semibold">{label(current)}</h2><small>{current.kind==='support'?'Échange privé avec ImmoPilot':current.members.map(m=>person(m)?.name??'Membre').join(', ')}</small></div>{current.kind==='group'&&current.createdBy===data.me.id&&<button className="btn-ghost" onClick={()=>{setTitle(current.title);setRename(!rename)}}>Renommer</button>}</header>
 {rename&&<form className="flex gap-2 p-3" onSubmit={e=>{e.preventDefault();void run({action:'rename',id,title},()=>setRename(false))}}><input className="input" aria-label="Titre du groupe" value={title} maxLength={100} onChange={e=>setTitle(e.target.value)}/><button className="btn-primary" disabled={busy||!title.trim()}>Enregistrer</button></form>}
 <div className="chat-history" aria-live="polite">{data.messages.map(m=><article key={m.id} className={`chat-message ${m.sender===data.me.id?'mine':''}`}><Pic p={person(m.sender)}/><div className="min-w-0"><small>{person(m.sender)?.name??'Membre'} · {new Date(m.at).toLocaleTimeString('fr-CA',{hour:'2-digit',minute:'2-digit'})}</small><p className="chat-bubble">{m.text}</p><div className="flex flex-wrap gap-1">{emojis.map(emoji=><button key={emoji} className={`chat-reaction ${m.reactions[emoji]?.includes(data.me.id)?'selected':''}`} aria-label={`Réagir ${emoji}`} disabled={busy} onClick={()=>run({action:'react',id,messageId:m.id,emoji})}>{emoji}{m.reactions[emoji]?.length||''}</button>)}</div></div></article>)}<div ref={bottom}/></div>
 <form className="chat-composer" onSubmit={e=>{e.preventDefault();void run({action:'send',id,text},()=>setText(''))}}>{emojiOpen&&<div className="flex gap-3 pb-2">{emojis.map(emoji=><button type="button" key={emoji} onClick={()=>setText(t=>t+emoji)}>{emoji}</button>)}</div>}<div className="flex items-end gap-2"><button className="btn-ghost" type="button" aria-label="Insérer un emoji" onClick={()=>setEmojiOpen(!emojiOpen)}><Smile size={21}/></button><textarea className="input min-h-12 resize-none" aria-label="Votre message" placeholder="Votre message…" rows={2} maxLength={5000} value={text} onChange={e=>setText(e.target.value)}/><button className="btn-primary" aria-label="Envoyer" disabled={busy||!text.trim()}><Send size={18}/></button></div></form></>}</section></div>
 {creating&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4"><form className="card max-h-[85dvh] w-full max-w-md overflow-y-auto p-5 space-y-4" onSubmit={e=>{e.preventDefault();void run({action:'create',kind,title,members},b=>{setId(b.id);setCreating(false)})}}><h2 className="text-xl font-semibold">Nouvelle conversation</h2><label className="block">Type<select className="input" value={kind} onChange={e=>{setKind(e.target.value);setMembers([])}}><option value="direct">Message privé</option><option value="group">Groupe</option></select></label>{kind==='group'&&<label className="block">Titre du groupe<input className="input" value={title} maxLength={100} onChange={e=>setTitle(e.target.value)} placeholder="Équipe marketing ✨" required/></label>}<fieldset><legend className="mb-2 font-medium">Membres de votre agence</legend>{data.peers.filter(p=>p.id!==data.me.id).map(p=><label key={p.id} className="flex items-center gap-3 py-2"><input type={kind==='direct'?'radio':'checkbox'} name="member" checked={members.includes(p.id)} onChange={e=>setMembers(kind==='direct'?[p.id]:e.target.checked?[...members,p.id]:members.filter(m=>m!==p.id))}/><Pic p={p}/>{p.name}</label>)}{data.peers.filter(p=>p.id!==data.me.id).length===0&&<p className="text-sm text-slate-500">Aucun autre membre actif dans votre agence.</p>}</fieldset><div className="flex justify-end gap-2"><button type="button" className="btn-ghost" onClick={()=>setCreating(false)}>Annuler</button><button className="btn-primary" disabled={busy||!members.length||kind==='group'&&!title.trim()}>Créer</button></div></form></div>}
 </div>
}
