import {useEffect,useState} from 'react'
import {language,locale} from '../lib/i18n'
const t=(a:string,b:string)=>language==='en'?b:a
type Event={id:string;subject:string;start:{dateTime:string};end:{dateTime:string};isOrganizer:boolean;isCancelled:boolean;location?:{displayName:string}}
export default function MicrosoftPanel(){
 const [events,setEvents]=useState<Event[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[canManage,setCanManage]=useState(false),[more,setMore]=useState(false),[editing,setEditing]=useState(''),[title,setTitle]=useState(''),[saved,setSaved]=useState(false)
 const agency=new URLSearchParams(location.search).get('agency');const endpoint='/api/microsoft'+(agency?'?agency='+encodeURIComponent(agency):'')
 async function load(){setBusy(true);setError('');try{const r=await fetch(endpoint);const b=await r.json();if(!r.ok)throw new Error(b.error);setEvents(b.events);setCanManage(b.canManage);setMore(b.hasMore)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{void load()},[endpoint])
 async function save(){setBusy(true);setError('');try{const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'update',id:editing,subject:title})});const b=await r.json();if(!r.ok)throw new Error(b.error);setEditing('');setSaved(true);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="mt-5 rounded-2xl border p-4"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-semibold">{t('Mon agenda Outlook · 31 prochains jours','My Outlook calendar · next 31 days')}</h3><button className="btn-outline" disabled={busy} onClick={()=>void load()}>{t('Actualiser','Refresh')}</button></div>{error&&<p role="alert" className="my-3 text-rose-700">{error}</p>}{saved&&<p role="status">{t('Titre enregistré dans Outlook.','Title saved in Outlook.')}</p>}{busy&&<p role="status">{t('Chargement…','Loading…')}</p>}{events.map(e=><article key={e.id} className="border-b py-4"><b>{e.subject}</b><p>{new Date(e.start.dateTime+'Z').toLocaleString(locale)} · {e.location?.displayName}</p>{e.isCancelled?<p>{t('Annulé','Cancelled')}</p>:canManage&&e.isOrganizer&&<button className="btn-outline mt-2" disabled={busy} onClick={()=>{setEditing(e.id);setTitle(e.subject);setSaved(false)}}>{t('Modifier le titre','Edit title')}</button>}{editing===e.id&&<form className="mt-3 space-y-3" onSubmit={event=>{event.preventDefault();void save()}}><label>{t('Titre du rendez-vous','Event title')}<input className="input" maxLength={255} required value={title} onChange={event=>setTitle(event.target.value)}/></label><p className="text-sm">{t('La modification sera envoyée à Outlook. Microsoft peut avertir les participants.','The change will be sent to Outlook. Microsoft may notify attendees.')}</p><button className="btn-primary" disabled={busy}>{t('Enregistrer dans Outlook','Save in Outlook')}</button><button type="button" className="btn-ghost" onClick={()=>setEditing('')}>{t('Annuler','Cancel')}</button></form>}</article>)}{!busy&&!error&&!events.length&&<p className="mt-3">{t('Aucun rendez-vous sur cette période.','No events in this period.')}</p>}{more&&<p>{t('Les 100 premiers résultats sont affichés.','Showing the first 100 results.')}</p>}</section>
}
