import {useEffect,useState} from 'react'
import {useStore} from '../lib/store'
import {language} from '../lib/i18n'
const t=(a:string,b:string)=>language==='en'?b:a
type Item={id:string;name:string;allowed:boolean;canManage:boolean;configured:boolean;connected:boolean;expired:boolean}
type Asset={id:string;name:string;kind:string}
export default function OAuthConnections(){const {mode}=useStore();const [items,setItems]=useState<Item[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [assets,setAssets]=useState<Asset[]>([]);const [selected,setSelected]=useState<string[]>([]);const [saved,setSaved]=useState(false);const agency=new URLSearchParams(location.search).get('agency');const endpoint='/api/connections'+(agency?'?agency='+encodeURIComponent(agency):'');
 async function load(){setError('');try{const r=await fetch(endpoint);const b=await r.json();if(!r.ok)throw new Error(b.error);setItems(b.connections)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{if(mode==='remote')void load()},[mode,endpoint]);
 async function action(provider:string,action:string){setBusy(true);setError('');try{const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider,action,selected})});const b=await r.json();if(!r.ok)throw new Error(b.error);if(b.url){location.assign(b.url);return}if(action==='select')setSaved(true);if(action==='disconnect'){setAssets([]);setSelected([])}await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function getAssets(){setBusy(true);setError('');try{const r=await fetch(endpoint+(agency?'&':'?')+'action=meta-assets');const b=await r.json();if(!r.ok)throw new Error(b.error);setAssets(b.assets);setSelected(b.selected);setSaved(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const result=new URLSearchParams(location.search).get('connection');
 return <section className="card p-6 mb-6"><h2 className="text-xl font-semibold">{t('Connecter mes comptes','Connect my accounts')}</h2><p className="my-3">{t('Autorisez ImmoPilot sur l’écran officiel du fournisseur, puis revenez ici. Connexions personnelles isolées par agence.','Authorize ImmoPilot on the provider’s official screen, then return here. Personal connections are isolated by agency.')}</p>{result&&<p role="status">{result==='success'?t('Autorisation enregistrée.','Authorization saved.'):t('Autorisation non terminée. Recommencez.','Authorization incomplete. Please try again.')}</p>}{error&&<p role="alert" className="text-rose-700 my-3">{error}</p>}{mode==='local'?<p>{t('Connectez-vous à votre agence pour autoriser vos comptes.','Sign in to your agency to authorize your accounts.')}</p>:<div className="grid gap-4 sm:grid-cols-2">{items.map(p=><div className="rounded-2xl border border-white/60 p-4" key={p.id}><h3 className="font-semibold">{p.name}</h3><p className="my-3">{!p.allowed?t('Accès refusé par votre agence','Access restricted by your agency'):p.connected?t('Autorisation enregistrée','Authorization saved'):p.expired?t('À reconnecter','Reconnect required'):p.configured?t('Prêt à connecter','Ready to connect'):t('Activation développeur requise','Developer setup required')}</p><div className="flex flex-wrap gap-2"><button className="btn-primary" disabled={!p.configured||!p.canManage||busy} onClick={()=>void action(p.id,'start')}>{p.connected?t('Renouveler','Reconnect'):t('Connecter','Connect')}</button>{p.connected&&<button className="btn-outline" disabled={busy||!p.canManage} onClick={()=>void action(p.id,'disconnect')}>{t('Déconnecter','Disconnect')}</button>}{p.id==='meta'&&p.connected&&<button className="btn-outline" disabled={busy||!p.allowed} onClick={()=>void getAssets()}>{t('Choisir les comptes','Select accounts')}</button>}</div></div>)}</div>}
 {assets.length>0&&<div className="mt-5"><h3 className="font-semibold">{t('Comptes autorisés par Meta','Accounts authorized by Meta')}</h3>{assets.map(a=><label className="flex items-center gap-3 py-3" key={a.id}><input type="checkbox" checked={selected.includes(a.id)} onChange={e=>{setSaved(false);setSelected(e.target.checked?[...selected,a.id]:selected.filter(x=>x!==a.id))}}/>{a.name} · {a.kind}</label>)}<button className="btn-primary" disabled={busy} onClick={()=>void action('meta','select')}>{t('Enregistrer la sélection','Save selection')}</button>{saved&&<p role="status">{t('Sélection enregistrée.','Selection saved.')}</p>}</div>}
 <p className="mt-4 text-sm text-slate-600">{t('La connexion autorise l’accès au compte. La publication, la programmation et les campagnes publicitaires ne sont pas encore disponibles dans cet écran. Déconnecter efface l’accès enregistré ici ; vous pouvez aussi révoquer ImmoPilot dans les réglages du fournisseur.','Connecting authorizes account access. Publishing, scheduling and ad campaigns are not yet available on this screen. Disconnecting removes stored access here; you can also revoke ImmoPilot in the provider settings.')}</p></section>
}
