import {useState} from 'react'
import {useStore} from '../lib/store'
import {mapProperty} from '../lib/property-import'
import type {Listing} from '../lib/types'
export default function PropertyImport(){
 const {db,me,upsert}=useStore();const [source,setSource]=useState(''),[preview,setPreview]=useState<Listing[]>([]),[error,setError]=useState(''),[done,setDone]=useState(false)
 async function read(file:File){setError('');setDone(false);setPreview([]);try{if(!source.trim())throw new Error('Indiquez la plateforme source avant de choisir le fichier.');if(file.size>2000000)throw new Error('Fichier limité à 2 Mo.');const body=JSON.parse(await file.text());const rows=Array.isArray(body)?body:body.value;if(!Array.isArray(rows)||!rows.length||rows.length>100)throw new Error('Fournissez 1 à 100 propriétés JSON.');const seen=new Set<string>();setPreview(rows.map(row=>{if(!row||typeof row!=='object'||Array.isArray(row))throw new Error('Fiche invalide.');const id=String(row.ListingKey??row.externalId??'');if(seen.has(id))throw new Error('Identifiant source en double : '+id);seen.add(id);const existing=db.listings.find(l=>l.external?.source===source.trim()&&l.external.id===id);return mapProperty(row,me.id,source.trim(),existing)}))}catch(e){setError((e as Error).message)}}
 return <section className="card p-5 mb-6"><h2 className="text-xl font-semibold">Importer des propriétés dans les fiches ImmoPilot</h2><p className="my-3">Import manuel JSON / champs RESO : adresse, ville, numéro d’inscription, prix, chambres, salles de bain, année, superficie, description et photo principale. La même source et le même identifiant mettent à jour la fiche existante, en conservant son courtier, ses documents, son marketing et ses champs absents de l’import.</p><label className="block">Plateforme source<input className="input mt-1" maxLength={100} value={source} onChange={e=>{setSource(e.target.value);setPreview([]);setDone(false)}}/></label><label className="block mt-3">Fichier de propriétés (.json)<input className="block mt-2" type="file" accept=".json,application/json" onChange={e=>{const file=e.target.files?.[0];if(file)void read(file);e.target.value=''}}/></label><details className="my-3"><summary>Format attendu</summary><pre className="overflow-x-auto p-3 text-xs">{'[{"ListingKey":"maison-123","UnparsedAddress":"123 rue Exemple","City":"Montréal","ListPrice":500000,"BedroomsTotal":3,"BathroomsTotalInteger":2,"StandardStatus":"Active"}]'}</pre><p>Les champs omis sont conservés. Aucun fichier importé ne supprime une fiche. L’import ne renvoie pas les modifications au fournisseur.</p></details>{error&&<p role="alert" className="text-rose-700">{error}</p>}{preview.length>0&&<><p className="font-semibold">Aperçu : {preview.length} fiche(s)</p><ul className="max-h-56 overflow-auto my-3">{preview.map(l=><li className="border-b py-2" key={l.id}>{db.listings.some(x=>x.id===l.id)?'Mise à jour':'Nouvelle fiche'} · {l.address} · {l.city} · {l.price.toLocaleString('fr-CA')} CAD</li>)}</ul><button className="btn-primary" onClick={()=>{preview.forEach(l=>upsert('listings',l));setPreview([]);setDone(true)}}>Importer dans les inscriptions</button></>}{done&&<p role="status">Import transmis à l’enregistrement. Consultez les fiches dans Inscriptions et vérifiez l’état de sauvegarde de votre espace.</p>}</section>
}
