import { createCipheriv, createDecipheriv, createHash, randomBytes } from 'node:crypto'
import { currentUser, loadAgencies, sameOrigin, json } from '../server/platform.js'
import { mutate, readJson } from '../server/storage.js'
const key=()=>{const secret=process.env.SESSION_SECRET;if(!secret)throw new Error('Configuration sécurisée manquante.');return createHash('sha256').update(secret+':calendly').digest()}
function seal(value:string){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key(),iv);const bytes=Buffer.concat([c.update(value,'utf8'),c.final()]);return [iv,c.getAuthTag(),bytes].map(x=>x.toString('base64url')).join('.')}
function unseal(value:string){const [iv,tag,bytes]=value.split('.').map(x=>Buffer.from(x,'base64url'));const c=createDecipheriv('aes-256-gcm',key(),iv);c.setAuthTag(tag);return Buffer.concat([c.update(bytes),c.final()]).toString('utf8')}
type Stored={token:string;user:string;name:string;at:string}|null
async function ctx(req:Request){const user=await currentUser(req);if(!user)return null;const agencyId=user.role==='superadmin'?new URL(req.url).searchParams.get('agency')||user.ownAgencyId:user.agencyId;const agency=(await loadAgencies()).find(x=>x.id===agencyId&&x.status==='actif');return agency?{user,path:`agencies/${agency.id}/connections/calendly/${user.id}.json`}:null}
async function call(token:string,path:string){const r=await fetch('https://api.calendly.com'+path,{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(r.status===401?'Accès Calendly expiré ou révoqué. Reconnectez votre compte.':r.status===403?'Permission Calendly insuffisante. Vérifiez les portées de votre jeton.':'Calendly est indisponible. Réessayez.');return r.json()}
export async function GET(req:Request){try{const c=await ctx(req);if(!c)return json({error:'Non connecté.'},401);const {data}=await readJson<Stored>(c.path);if(!data)return json({connected:false,events:[],types:[]});if(new URL(req.url).searchParams.get('action')==='status')return json({connected:true,name:data.name,at:data.at});const token=unseal(data.token);const [events,types]=await Promise.all([call(token,'/scheduled_events?'+new URLSearchParams({user:data.user,status:'active',min_start_time:new Date().toISOString(),sort:'start_time:asc',count:'50'})),call(token,'/event_types?'+new URLSearchParams({user:data.user,active:'true',count:'50'}))]);return json({connected:true,name:data.name,events:events.collection??[],types:types.collection??[],hasMore:!!events.pagination?.next_page_token})}catch(e){return json({error:(e as Error).message},502)}}
export async function POST(req:Request){if(!sameOrigin(req))return json({error:'Origine refusée.'},403);try{const c=await ctx(req);if(!c)return json({error:'Non connecté.'},401);const b=await req.json();if(b.action==='disconnect'){await mutate<Stored>(c.path,()=>null,()=>null);return json({ok:true})}if(b.action!=='connect'||typeof b.token!=='string'||b.token.length<20||b.token.length>10000)return json({error:'Jeton invalide.'},400);const profile=await call(b.token,'/users/me');const u=profile.resource;if(!u?.uri?.startsWith('https://api.calendly.com/users/'))return json({error:'Compte Calendly invalide.'},400);const encrypted=seal(b.token);await mutate<Stored>(c.path,()=>null,()=>({token:encrypted,user:u.uri,name:u.name,at:new Date().toISOString()}));return json({ok:true,name:u.name})}catch(e){return json({error:(e as Error).message},502)}}
